// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Drawing;
using System.Diagnostics;
using Microsoft.VisualBasic;

namespace Morysoft.MorySnip.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("Morysoft.MorySnip.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823643_doc_edit
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823643_doc_edit", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823655_folder_open
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823655_folder_open", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823693_clipboard_cut
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823693_clipboard_cut", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823721_clipboard_past
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823721_clipboard_past", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823758_monitor
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823758_monitor", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823810_save
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823810_save", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823810_saveas
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823810_saveas", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823827_doc_delete
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823827_doc_delete", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371823849_trash
        {
            get
            {
                var obj = ResourceManager.GetObject("1371823849_trash", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371824300_clipboard_copy
        {
            get
            {
                var obj = ResourceManager.GetObject("1371824300_clipboard_copy", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1371996336_browser
        {
            get
            {
                var obj = ResourceManager.GetObject("1371996336_browser", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _32_1_
        {
            get
            {
                var obj = ResourceManager.GetObject("32[1]", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _select
        {
            get
            {
                var obj = ResourceManager.GetObject("_select", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrow
        {
            get
            {
                var obj = ResourceManager.GetObject("arrow", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Arrow2___left
        {
            get
            {
                var obj = ResourceManager.GetObject("Arrow2 - left", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Arrow2___right
        {
            get
            {
                var obj = ResourceManager.GetObject("Arrow2 - right", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap black_white
        {
            get
            {
                var obj = ResourceManager.GetObject("black_white", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap blur
        {
            get
            {
                var obj = ResourceManager.GetObject("blur", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap clipboard_copy
        {
            get
            {
                var obj = ResourceManager.GetObject("clipboard_copy", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap clipboard_cut
        {
            get
            {
                var obj = ResourceManager.GetObject("clipboard_cut", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap close
        {
            get
            {
                var obj = ResourceManager.GetObject("close", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap doc_plus_32
        {
            get
            {
                var obj = ResourceManager.GetObject("doc_plus_32", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap document
        {
            get
            {
                var obj = ResourceManager.GetObject("document", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap facebook_48
        {
            get
            {
                var obj = ResourceManager.GetObject("facebook_48", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap fill
        {
            get
            {
                var obj = ResourceManager.GetObject("fill", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap free
        {
            get
            {
                var obj = ResourceManager.GetObject("free", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Fullscreen
        {
            get
            {
                var obj = ResourceManager.GetObject("Fullscreen", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap highlight
        {
            get
            {
                var obj = ResourceManager.GetObject("highlight", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap iconic_folder
        {
            get
            {
                var obj = ResourceManager.GetObject("iconic_folder", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap iconic_fullscreen
        {
            get
            {
                var obj = ResourceManager.GetObject("iconic_fullscreen", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap iconic_new_window
        {
            get
            {
                var obj = ResourceManager.GetObject("iconic_new_window", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap iconic_x
        {
            get
            {
                var obj = ResourceManager.GetObject("iconic_x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://www.iconfinder.com/iconsets/iconic-1.
        /// </summary>
        internal static string IconsLink
        {
            get
            {
                return ResourceManager.GetString("IconsLink", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap line
        {
            get
            {
                var obj = ResourceManager.GetObject("line", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Numbers
        {
            get
            {
                var obj = ResourceManager.GetObject("Numbers", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Ok
        {
            get
            {
                var obj = ResourceManager.GetObject("Ok", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap oval
        {
            get
            {
                var obj = ResourceManager.GetObject("oval", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PENCIL
        {
            get
            {
                var obj = ResourceManager.GetObject("PENCIL", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Press Left Click to view Options.
        /// </summary>
        internal static string PressLeftClickToViewOptions
        {
            get
            {
                return ResourceManager.GetString("PressLeftClickToViewOptions", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Press Right Click to view Options.
        /// </summary>
        internal static string PressRightClickToViewOptions
        {
            get
            {
                return ResourceManager.GetString("PressRightClickToViewOptions", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap rect
        {
            get
            {
                var obj = ResourceManager.GetObject("rect", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap reset_select
        {
            get
            {
                var obj = ResourceManager.GetObject("reset_select", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap round_plus_32
        {
            get
            {
                var obj = ResourceManager.GetObject("round_plus_32", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Star
        {
            get
            {
                var obj = ResourceManager.GetObject("Star", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap StarEmpty
        {
            get
            {
                var obj = ResourceManager.GetObject("StarEmpty", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap stock_filters_invert_16
        {
            get
            {
                var obj = ResourceManager.GetObject("stock_filters-invert-16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap transform_crop
        {
            get
            {
                var obj = ResourceManager.GetObject("transform_crop", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}

